/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package planningformen.ui.gui;
import planningformen.ui.gui.*;
/**
 *
 * @author Morten
 */
public class CreateMainPanel extends javax.swing.JPanel
{

    /**
     * Creates new form CreateMainPanel
     */
    public CreateMainPanel()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        createCarPanel1 = new planningformen.ui.gui.CreateCarPanel();
        createCustomerPanel1 = new planningformen.ui.gui.CreateCustomerPanel();
        createEmployee2 = new planningformen.ui.gui.CreateEmployee();
        createServicePanel1 = new planningformen.ui.gui.CreateServicePanel();
        createTyrePanel1 = new planningformen.ui.gui.CreateTyrePanel();
        createSalePanel1 = new planningformen.ui.gui.CreateSalePanel();
        jLabel1 = new javax.swing.JLabel();

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jTabbedPane1.addTab("Car", createCarPanel1);

        javax.swing.GroupLayout createCustomerPanel1Layout = new javax.swing.GroupLayout(createCustomerPanel1);
        createCustomerPanel1.setLayout(createCustomerPanel1Layout);
        createCustomerPanel1Layout.setHorizontalGroup(
            createCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        createCustomerPanel1Layout.setVerticalGroup(
            createCustomerPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Customer", createCustomerPanel1);

        javax.swing.GroupLayout createEmployee2Layout = new javax.swing.GroupLayout(createEmployee2);
        createEmployee2.setLayout(createEmployee2Layout);
        createEmployee2Layout.setHorizontalGroup(
            createEmployee2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        createEmployee2Layout.setVerticalGroup(
            createEmployee2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Employee", createEmployee2);

        javax.swing.GroupLayout createServicePanel1Layout = new javax.swing.GroupLayout(createServicePanel1);
        createServicePanel1.setLayout(createServicePanel1Layout);
        createServicePanel1Layout.setHorizontalGroup(
            createServicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        createServicePanel1Layout.setVerticalGroup(
            createServicePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Service", createServicePanel1);

        javax.swing.GroupLayout createTyrePanel1Layout = new javax.swing.GroupLayout(createTyrePanel1);
        createTyrePanel1.setLayout(createTyrePanel1Layout);
        createTyrePanel1Layout.setHorizontalGroup(
            createTyrePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        createTyrePanel1Layout.setVerticalGroup(
            createTyrePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tyre", createTyrePanel1);

        javax.swing.GroupLayout createSalePanel1Layout = new javax.swing.GroupLayout(createSalePanel1);
        createSalePanel1.setLayout(createSalePanel1Layout);
        createSalePanel1Layout.setHorizontalGroup(
            createSalePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        createSalePanel1Layout.setVerticalGroup(
            createSalePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 505, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sale", createSalePanel1);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Create");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(411, 411, 411)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private planningformen.ui.gui.CreateCarPanel createCarPanel1;
    private planningformen.ui.gui.CreateCustomerPanel createCustomerPanel1;
    private planningformen.ui.gui.CreateEmployee createEmployee2;
    private planningformen.ui.gui.CreateSalePanel createSalePanel1;
    private planningformen.ui.gui.CreateServicePanel createServicePanel1;
    private planningformen.ui.gui.CreateTyrePanel createTyrePanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
