/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package planningformen.ui.gui;

import java.util.List;
import javax.swing.DefaultListModel;
import planningformen.application.IServiceController;
import planningformen.application.ServiceController;
import planningformen.domain.financeandefficiency.Garage;
import planningformen.domain.financeandefficiency.Service;
import planningformen.domain.financeandefficiency.ServiceType;

/**
 *
 * @author Cymon343
 */
public class GaragesPanel extends javax.swing.JPanel
{
    private List<Service> _jobs;
    private IServiceController _controller;
    private DefaultListModel _dieselList, _normalList, _tuningList, _finishedList;
    private Garage[] _garages;
    /**
     * Creates new form Garage1
     */
    public GaragesPanel()
    {
        initComponents();
        
        _dieselList = new DefaultListModel();
        _normalList = new DefaultListModel();
        _tuningList = new DefaultListModel();
        _finishedList = new DefaultListModel();
        
        
        dieselList.setModel(_dieselList);
        normalList.setModel(_normalList);
        tuningList.setModel(_tuningList);
        finsihedList.setModel(_finishedList);
        _controller = new ServiceController();
        _garages = _controller.getGarages();
        _jobs = _controller.getServices();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        normalList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnStartNormal = new javax.swing.JButton();
        btnFinishNormal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dieselList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnFinishDiesel = new javax.swing.JButton();
        btnStartDiesel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tuningList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnStartTuning = new javax.swing.JButton();
        btnFinishTuning = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFieldDescription = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        whatever = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblGarage = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnReload = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        finsihedList = new javax.swing.JList();
        jLabel11 = new javax.swing.JLabel();

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        normalList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        normalList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                normalListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(normalList);

        jLabel2.setText("Garage 2 Prioritized Job List:");

        jLabel8.setText("Normal");

        btnStartNormal.setText("Start Job");
        btnStartNormal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStartNormal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartNormalActionPerformed(evt);
            }
        });

        btnFinishNormal.setText("Finish Job");
        btnFinishNormal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFinishNormal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinishNormalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnStartNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinishNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartNormal)
                    .addComponent(btnFinishNormal))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dieselList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        dieselList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                dieselListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(dieselList);

        jLabel3.setText("Garage 1 Prioritized Job List:");

        jLabel10.setText("Diesel");

        btnFinishDiesel.setText("Finish Job");
        btnFinishDiesel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFinishDiesel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinishDieselActionPerformed(evt);
            }
        });

        btnStartDiesel.setText("Start Job");
        btnStartDiesel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStartDiesel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartDieselActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnStartDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinishDiesel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinishDiesel)
                    .addComponent(btnStartDiesel))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tuningList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        tuningList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                tuningListValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(tuningList);

        jLabel6.setText("Garage 3 Prioritized Job List:");

        jLabel7.setText("Tuning");

        btnStartTuning.setText("Start Job");
        btnStartTuning.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnStartTuning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartTuningActionPerformed(evt);
            }
        });

        btnFinishTuning.setText("Finish Job");
        btnFinishTuning.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFinishTuning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinishTuningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnStartTuning, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinishTuning, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStartTuning)
                    .addComponent(btnFinishTuning))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel9.setText("Description:");

        txtFieldDescription.setColumns(20);
        txtFieldDescription.setRows(5);
        jScrollPane2.setViewportView(txtFieldDescription);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        whatever.setText("Type:");

        jLabel4.setText("State:");

        lblGarage.setText("-");

        lblState.setText("-");

        lblType.setText("-");

        jLabel5.setText("Garage:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(whatever)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGarage, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblGarage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(whatever)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReload.setText("Reload Lists");
        btnReload.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReload.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        finsihedList.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        finsihedList.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                finsihedListValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(finsihedList);

        jLabel11.setText("Finsihed Jobs");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jPanel6, jPanel7});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel3, jPanel4, jPanel5});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanel6, jPanel7});

    }// </editor-fold>//GEN-END:initComponents

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReloadActionPerformed
    {//GEN-HEADEREND:event_btnReloadActionPerformed
        _controller.planJobPriorityForMechanics();
        applySearchResults();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void dieselListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_dieselListValueChanged
    {//GEN-HEADEREND:event_dieselListValueChanged
        displayDieselJob(dieselList.getSelectedIndex());
    }//GEN-LAST:event_dieselListValueChanged

    private void normalListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_normalListValueChanged
    {//GEN-HEADEREND:event_normalListValueChanged
        displayNormalJob(normalList.getSelectedIndex());
    }//GEN-LAST:event_normalListValueChanged

    private void tuningListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_tuningListValueChanged
    {//GEN-HEADEREND:event_tuningListValueChanged
        displayTuningJob(tuningList.getSelectedIndex());
    }//GEN-LAST:event_tuningListValueChanged

    private void finsihedListValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_finsihedListValueChanged
    {//GEN-HEADEREND:event_finsihedListValueChanged
        displayFinishedJob(finsihedList.getSelectedIndex());
    }//GEN-LAST:event_finsihedListValueChanged

    private void btnStartNormalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartNormalActionPerformed
    {//GEN-HEADEREND:event_btnStartNormalActionPerformed
        Service s = _garages[1].getJobs().get(normalList.getSelectedIndex());
        _controller.startJob(s, ServiceType.NORMAL);
        _controller.planJobPriorityForMechanics();
        applySearchResults();
    }//GEN-LAST:event_btnStartNormalActionPerformed

    private void btnStartTuningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartTuningActionPerformed
    {//GEN-HEADEREND:event_btnStartTuningActionPerformed
        Service s = _garages[2].getJobs().get(tuningList.getSelectedIndex());
        _controller.startJob(s, ServiceType.TUNING);
        _controller.planJobPriorityForMechanics();
        applySearchResults();
    }//GEN-LAST:event_btnStartTuningActionPerformed

    private void btnStartDieselActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnStartDieselActionPerformed
    {//GEN-HEADEREND:event_btnStartDieselActionPerformed
        Service s = _garages[0].getJobs().get(dieselList.getSelectedIndex());
        _controller.startJob(s, ServiceType.DIESEL);
        _controller.planJobPriorityForMechanics();
        applySearchResults();
    }//GEN-LAST:event_btnStartDieselActionPerformed

    private void btnFinishDieselActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinishDieselActionPerformed
    {//GEN-HEADEREND:event_btnFinishDieselActionPerformed
        Service s = _garages[0].getJobs().get(dieselList.getSelectedIndex());
        _controller.finishJob(s, ServiceType.DIESEL);
        _controller.planJobPriorityForMechanics();
        applySearchResults();
    }//GEN-LAST:event_btnFinishDieselActionPerformed

    private void btnFinishNormalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinishNormalActionPerformed
    {//GEN-HEADEREND:event_btnFinishNormalActionPerformed
        Service s = _garages[1].getJobs().get(normalList.getSelectedIndex());
        _controller.finishJob(s, ServiceType.NORMAL);
        _controller.planJobPriorityForMechanics();
        applySearchResults();
    }//GEN-LAST:event_btnFinishNormalActionPerformed

    private void btnFinishTuningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinishTuningActionPerformed
    {//GEN-HEADEREND:event_btnFinishTuningActionPerformed
        Service s = _garages[2].getJobs().get(tuningList.getSelectedIndex());
        _controller.finishJob(s, ServiceType.TUNING);
        _controller.planJobPriorityForMechanics();
        applySearchResults();
    }//GEN-LAST:event_btnFinishTuningActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinishDiesel;
    private javax.swing.JButton btnFinishNormal;
    private javax.swing.JButton btnFinishTuning;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnStartDiesel;
    private javax.swing.JButton btnStartNormal;
    private javax.swing.JButton btnStartTuning;
    private javax.swing.JList dieselList;
    private javax.swing.JList finsihedList;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblGarage;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblType;
    private javax.swing.JList normalList;
    private javax.swing.JList tuningList;
    private javax.swing.JTextArea txtFieldDescription;
    private javax.swing.JLabel whatever;
    // End of variables declaration//GEN-END:variables
    
    private void applySearchResults()
    {
        
        _dieselList.clear();
        _normalList.clear();
        _tuningList.clear();
        _finishedList.clear();
        
        for (Service s : _garages[0].getJobs())
        {
            _dieselList.addElement(s);
        }
        for (Service s : _garages[1].getJobs())
        {
            _normalList.addElement(s);
        }
        for (Service s : _garages[2].getJobs())
        {
            _tuningList.addElement(s);
        }
        for (Service s : _controller.getFinishedJobs())
        {
            _finishedList.addElement(s);
        }
    }
    
    
    private void displayDieselJob(int index)
    {
        if (index < 0)
        {
            return;
        }
        if(_dieselList == null)
            return;
        if(_dieselList.size() > 0)
        {
            Service s = (Service) _dieselList.get(index);
            
            switch (s.getType().getNumericValue())
            {
                case 1:
                    lblType.setText("Diesel");
                    break;
                case 2:
                    lblType.setText("Normal");
                    break;
                case 3:
                    lblType.setText("Tuning");
                    break;
            }
            
            switch (s.getState().getNumericValue())
            {
                case 1:
                    lblState.setText("Pending");
                    break;
                case 2:
                    lblState.setText("Reserved");
                    break;
                case 3:
                    lblState.setText("Started");
                    break;
                case 4:
                    lblState.setText("Finished");
                    break;
            }
            
            switch (s.getGarageType().getNumericValue())
            {
                case 1:
                    lblGarage.setText("Diesel");
                    break;
                case 2:
                    lblGarage.setText("Normal");
                    break;
                case 3:
                    lblGarage.setText("Tuning");
                    break;
            }
            txtFieldDescription.setText(s.getDescription());
        }
    }
    
    private void displayNormalJob(int index)
    {
        if (index < 0)
        {
            return;
        }
        if(_normalList == null)
            return;
        if(_normalList.size() > 0)
        {
            Service s = (Service) _normalList.get(index);
            
            switch (s.getType().getNumericValue())
            {
                case 1:
                    lblType.setText("Diesel");
                    break;
                case 2:
                    lblType.setText("Normal");
                    break;
                case 3:
                    lblType.setText("Tuning");
                    break;
            }
            
            switch (s.getState().getNumericValue())
            {
                case 1:
                    lblState.setText("Pending");
                    break;
                case 2:
                    lblState.setText("Reserved");
                    break;
                case 3:
                    lblState.setText("Started");
                    break;
                case 4:
                    lblState.setText("Finished");
                    break;
            }
            
            switch (s.getGarageType().getNumericValue())
            {
                case 1:
                    lblGarage.setText("Diesel");
                    break;
                case 2:
                    lblGarage.setText("Normal");
                    break;
                case 3:
                    lblGarage.setText("Tuning");
                    break;
            }
            txtFieldDescription.setText(s.getDescription());
        }
    }

    private void displayTuningJob(int index)
    {
        if (index < 0)
        {
            return;
        }
        if(_tuningList == null)
            return;
        if(_tuningList.size() > 0)
        {
            Service s = (Service) _tuningList.get(index);
            
            switch (s.getType().getNumericValue())
            {
                case 1:
                    lblType.setText("Diesel");
                    break;
                case 2:
                    lblType.setText("Normal");
                    break;
                case 3:
                    lblType.setText("Tuning");
                    break;
            }
            
            switch (s.getState().getNumericValue())
            {
                case 1:
                    lblState.setText("Pending");
                    break;
                case 2:
                    lblState.setText("Reserved");
                    break;
                case 3:
                    lblState.setText("Started");
                    break;
                case 4:
                    lblState.setText("Finished");
                    break;
            }
            
            switch (s.getGarageType().getNumericValue())
            {
                case 1:
                    lblGarage.setText("Diesel");
                    break;
                case 2:
                    lblGarage.setText("Normal");
                    break;
                case 3:
                    lblGarage.setText("Tuning");
                    break;
            }
            txtFieldDescription.setText(s.getDescription());
        }
    }

    private void displayFinishedJob(int index)
    {
        if (index < 0)
        {
            return;
        }
        if(_finishedList == null)
            return;
        if(_finishedList.size() > 0)
        {
            Service s = (Service) _finishedList.get(index);
            
            switch (s.getType().getNumericValue())
            {
                case 1:
                    lblType.setText("Diesel");
                    break;
                case 2:
                    lblType.setText("Normal");
                    break;
                case 3:
                    lblType.setText("Tuning");
                    break;
            }
            
            switch (s.getState().getNumericValue())
            {
                case 1:
                    lblState.setText("Pending");
                    break;
                case 2:
                    lblState.setText("Reserved");
                    break;
                case 3:
                    lblState.setText("Started");
                    break;
                case 4:
                    lblState.setText("Finished");
                    break;
            }
            
            switch (s.getGarageType().getNumericValue())
            {
                case 1:
                    lblGarage.setText("Diesel");
                    break;
                case 2:
                    lblGarage.setText("Normal");
                    break;
                case 3:
                    lblGarage.setText("Tuning");
                    break;
            }
            txtFieldDescription.setText(s.getDescription());
        }
    }
    
    
    
}
